# GPIO for LED
CONFIG_GPIO=y

# Console and Logging
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Stack Size (Fix for OLED buffer)
CONFIG_MAIN_STACK_SIZE=4096

# I2C and Display
CONFIG_I2C=y
CONFIG_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_CHARACTER_FRAMEBUFFER=y

# SPI and Flash
CONFIG_SPI=y
CONFIG_FLASH=y
CONFIG_SPI_NOR=y

# Sensors
CONFIG_SENSOR=y
CONFIG_BME280=y
