# Enable Simulation Drivers
CONFIG_GPIO_EMUL=y
CONFIG_SENSOR_DUMMY=y
CONFIG_FLASH_SIMULATOR=y
CONFIG_SDL_DISPLAY=n
CONFIG_DUMMY_DISPLAY=y

# These were board-specific in prj.conf, but we need counterparts here
CONFIG_SSD1306=n
CONFIG_BME280=n
CONFIG_SPI_NOR=n
