# Enable Simulation Drivers
CONFIG_GPIO_EMUL=n
CONFIG_FLASH_SIMULATOR=n
CONFIG_SPI=n
CONFIG_SPI_NOR=n

# Drivers
CONFIG_SENSOR=n
CONFIG_LM75=n
CONFIG_BME280=n

CONFIG_DISPLAY=n
CONFIG_DUMMY_DISPLAY=n
CONFIG_SSD1306=n

# Disable SDL
CONFIG_SDL_DISPLAY=n

# Console
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
